### ISSUE TITLE
No way to get into the low code editor

### ISSUE THREAD

**Issue by juan-libros** [dittofeed/dittofeed#1093]
Hey there, 

I was reading the [documentation](https://docs.dittofeed.com/resources/templates/email-editor#low-code-editor) and found the low code editor feature. However, I can not find a way of activating it replacing the MJML syntax in the body field. 

![image](https://github.com/user-attachments/assets/c3ae549b-c8ea-46f3-8357-018a19585f9d)

Even when adding the url query parameters that the screenshot in the documentation shows it still does not activate the low code editor feature `https://demo.dittofeed.com/dashboard/templates/email/860ff0f5-7b7d-40bd-a554-d2862f0f346b?name=example&emailContentType=LowCode`

As you can see I am trying this in the example instance provided in the documentation but I also tried running it locally as per [this guide](https://docs.dittofeed.com/deployment/self-hosted/docker-compose) and it still did not work.

Even after that, I decided to follow [this guide](https://docs.dittofeed.com/contributing/running-locally) instead and I could not make the following commands run without error on the [latest git commit to the main branch](https://github.com/dittofeed/dittofeed/commit/0bee086feebc517731eb3a48e0e7ba5e98cf5db0).

```
./dev-setup.sh
```
which failed with error:

![image](https://github.com/user-attachments/assets/1a057765-ea42-404f-99b5-218514644b25)

Thank you for your time.

**Comment by maxgurewitz** [comment]
Hi @juan-libros the low code builder is only available in the upcoming v0.18.0 release, to be released tomorrow!

**Comment by juan-libros** [comment]
Awesome! I'll wait then. Thanks for your quick response. Do you want me to close this issue and open a new one for the build errors?

**Comment by maxgurewitz** [comment]
No, let me get out a quick fix for that build error!

**Comment by maxgurewitz** [comment]
https://github.com/dittofeed/dittofeed/pull/1094

**Comment by maxgurewitz** [comment]
Also v0.18.0 published now.

**Comment by juan-libros** [comment]
> @juan-libros can you try again?

Hey, unfortunately still not working. Similar build error came up while following this guide https://docs.dittofeed.com/contributing/running-locally. However I made it work after reading [your commit](https://github.com/dittofeed/dittofeed/commit/0e22b00199e1386d6377edb70fc894a3b3b4a4ee) by doing this:

```sh
# dev-setup.sh

#!/bin/bash
set -euo pipefail

yarn
yarn workspace emailo build # build first
yarn workspace backend-lib prisma generate
yarn workspace backend-lib tsc --build
yarn workspace dashboard tsc --build
yarn admin bootstrap
```

**Comment by maxgurewitz** [comment]
That looks right! Will incorporate the change.
