### ISSUE TITLE
Unhandled runtime error when togggling "View Draft" in low code editor

### ISSUE THREAD

**Issue by juan-libros** [dittofeed/dittofeed#1102]
Error: 

![image](https://github.com/user-attachments/assets/f2d34fe1-4f8d-4931-8680-e2375e542140)

Toggle:

![image](https://github.com/user-attachments/assets/128c3724-9ef7-4e66-9629-0485bffa7002)

**Comment by maxgurewitz** [comment]
https://github.com/dittofeed/dittofeed/pull/1106

**Comment by maxgurewitz** [comment]
fixed in above PR
