### ISSUE TITLE
Low Code editor breaks liquid templating by replacing double quotes

### ISSUE THREAD

**Issue by juan-libros** [dittofeed/dittofeed#1104]
When inserting double quotes "something" in the Low Code editor it gets replaced with “something“ which are not the same double quotes, this invalidates liquid templates so as a workaround I have to create those templates in my a separate editor and then paste them in Dittofeed.

**Comment by maxgurewitz** [comment]
@juan-libros could explain a little bit more, are you trying to type liquid syntax directly into the low code editor?

**Comment by juan-libros** [comment]
Right, I see. Yes I am putting straight liquid syntax into the low code editor. I am trying to follow with some of the examples you guys have in the [documentation around `performed user properties`](https://docs.dittofeed.com/resources/user-property-types/trait#example-use-case-recommendations) but on the new Low Code editor.

**Comment by maxgurewitz** [comment]
https://github.com/dittofeed/dittofeed/pull/1113 @juan-libros 🙏 this should address your use case!
