### ISSUE TITLE
Deleted user still appears in the users table

### ISSUE THREAD

**Issue by juan-libros** [dittofeed/dittofeed#1109]
when deleting a user in the user's details page `https://app.dittofeed.com/dashboard/users/1` via the trash can button in the top right corner, I get a green toast saying that the user has been deleted, yet in the table at `https://app.dittofeed.com/dashboard/users/` I can still see the user, it just does not have any properties but the id and the segments it belonged to are still there. Refreshed the page, restarted the servers and the user is still there.

I expected the user to be completely deleted and to not appear in the table at all after deletion. Is this the intended behaviour?

**Comment by maxgurewitz** [comment]
@juan-libros let me take a look!

**Comment by maxgurewitz** [comment]
I'm not able to reproduce this behavior. @juan-libros would you be able to take a screen recording? 🙏

**Comment by juan-libros** [comment]
Sorry for the late response.

[Screencast from 2024-10-29 11-17-17.webm](https://github.com/user-attachments/assets/ddacb1bf-1d00-4b43-869c-fd032e19a7e0)

**Comment by maxgurewitz** [comment]
Thanks for this!

**Comment by maxgurewitz** [comment]
PR to fix https://github.com/dittofeed/dittofeed/pull/1116
