### ISSUE TITLE
[DF-500] Implement a mailchimp provider

### ISSUE THREAD

**Issue by maxgurewitz** [dittofeed/dittofeed#1130]
Implement support for [Mailchimp](https://mailchimp.com/) and mandrill as an email service provider.

Add a new `PersistedEmailProvider` type:

[https://github.com/dittofeed/dittofeed/blob/098d153f764da44f4df48b8930f97a431f240883/packages/isomorphic-lib/src/types.ts#L1465-L1472](https://github.com/dittofeed/dittofeed/blob/098d153f764da44f4df48b8930f97a431f240883/packages/isomorphic-lib/src/types.ts#L1465-L1472)

Add new `EmailServiceProviderSuccess` type:

[https://github.com/dittofeed/dittofeed/blob/098d153f764da44f4df48b8930f97a431f240883/packages/isomorphic-lib/src/types.ts#L3068-L3075](https://github.com/dittofeed/dittofeed/blob/098d153f764da44f4df48b8930f97a431f240883/packages/isomorphic-lib/src/types.ts#L3068-L3075)

Add new `EmailServiceProviderFailure` type:

[https://github.com/dittofeed/dittofeed/blob/098d153f764da44f4df48b8930f97a431f240883/packages/isomorphic-lib/src/types.ts#L3275-L3281](https://github.com/dittofeed/dittofeed/blob/098d153f764da44f4df48b8930f97a431f240883/packages/isomorphic-lib/src/types.ts#L3275-L3281)

Add new `EmailProviderSecret` type:

[https://github.com/dittofeed/dittofeed/blob/098d153f764da44f4df48b8930f97a431f240883/packages/isomorphic-lib/src/types.ts#L3610-L3617](https://github.com/dittofeed/dittofeed/blob/098d153f764da44f4df48b8930f97a431f240883/packages/isomorphic-lib/src/types.ts#L3610-L3617)

Error handling for the `/templates/test` api endpoint:

[https://github.com/dittofeed/dittofeed/blob/098d153f764da44f4df48b8930f97a431f240883/packages/api/src/controllers/contentController.ts#L418-L437](https://github.com/dittofeed/dittofeed/blob/098d153f764da44f4df48b8930f97a431f240883/packages/api/src/controllers/contentController.ts#L418-L437)

A webhook for updating the status of sent emails:

[https://github.com/dittofeed/dittofeed/blob/098d153f764da44f4df48b8930f97a431f240883/packages/api/src/controllers/webhooksController.ts#L68-L80](https://github.com/dittofeed/dittofeed/blob/098d153f764da44f4df48b8930f97a431f240883/packages/api/src/controllers/webhooksController.ts#L68-L80)

Handle the email provider type when sending messages:

[https://github.com/dittofeed/dittofeed/blob/098d153f764da44f4df48b8930f97a431f240883/packages/backend-lib/src/messaging.ts#L899-L909](https://github.com/dittofeed/dittofeed/blob/098d153f764da44f4df48b8930f97a431f240883/packages/backend-lib/src/messaging.ts#L899-L909)

Create the email provider:

[https://github.com/dittofeed/dittofeed/blob/098d153f764da44f4df48b8930f97a431f240883/packages/backend-lib/src/messaging/email.ts#L143-L152](https://github.com/dittofeed/dittofeed/blob/098d153f764da44f4df48b8930f97a431f240883/packages/backend-lib/src/messaging/email.ts#L143-L152)

Add Place in Settings to configure email provider:

[https://github.com/dittofeed/dittofeed/blob/098d153f764da44f4df48b8930f97a431f240883/packages/dashboard/src/pages/settings.page.tsx#L1060-L1072](https://github.com/dittofeed/dittofeed/blob/098d153f764da44f4df48b8930f97a431f240883/packages/dashboard/src/pages/settings.page.tsx#L1060-L1072)

See this previous issue as a reference: [https://github.com/dittofeed/dittofeed/issues/641](https://github.com/dittofeed/dittofeed/issues/641)

<sub>From [SyncLinear.com](https://synclinear.com) | [DF-500](https://linear.app/dittofeed/issue/DF-500/implement-a-mailchimp-provider)</sub>

**Comment by neo773** [comment]
/attempt #1130

As discussed in private on Discord

**Comment by Gmin2** [comment]
if already assigned to a particular contributor it would make sense to post it in the comments earlier

**Comment by maxgurewitz** [comment]
Hi @Gmin2 I assigned it as quickly as I could! I believe it was within 15mins of issue creation. Apologies for the inconvenience!
