### ISSUE TITLE
/api/public/apps/identify not adding user properties

### ISSUE THREAD

**Issue by walseb** [dittofeed/dittofeed#1135]
Hello!

I'm using Docker with Dittofeed `dittofeed/dittofeed-lite:${IMAGE_TAG:-v0.19.0}`

When I add a user like this:

```
"curl --request POST \\
  --url 'http://IP:3000/api/public/apps/identify' \\
  --header 'Content-Type: application/json' \\
  --header 'PublicWriteKey: ...' \\
  --header 'authorization: ...' \\
  --data '{
"messageId": "ID",
"userId": "testing@testing.com",
"traits": {
"email": "testing@testing.com",
"imported-user-segment": "4"
}';
```

only the ID and email shows up:
![2024-11-15 Fri 17:26 l9VXJ9](https://github.com/user-attachments/assets/1bc4e6c6-df52-4af5-900a-ac2d87ec7f5e)
![2024-11-15 Fri 17:26 CJ59xV](https://github.com/user-attachments/assets/ec0ce392-6858-41f7-821d-7cb7c92c5f29)

However, when I go into the events, I can see that it was supposed to be added when I hover over the properties field:
![2024-11-15 Fri 17:26 kiP9Wy](https://github.com/user-attachments/assets/54525451-654e-49bf-8f12-da1940513734)

I have added "imported-user-segment" as a user property, so it should show up:
![2024-11-15 Fri 17:31 TS6QT7](https://github.com/user-attachments/assets/d72a5fbb-389f-43b8-a342-734f9c01c137)

But I can't find it when searching for users and such:
![2024-11-15 Fri 17:31 WAqzop](https://github.com/user-attachments/assets/a9638a8c-cb2f-41fc-8526-fc5fb58ecc2a)

Thoughts?

I tried adding in the user property again with the `/api/admin/user-properties/` endpoint, but I couldn't figure out what the `name` property was: https://docs.dittofeed.com/api-reference/auto/user-properties/put-apiadminuser-properties

Thanks for any help!

**Comment by maxgurewitz** [comment]
Hi @walseb have you seen this?

https://docs.dittofeed.com/guide/faq

**Comment by walseb** [comment]
Thank you! I will have a look. 

It could be that the properties worker isn't running.

**Comment by walseb** [comment]
Yes, that's the issue. It's getting a syntax error when parsing:

```
Nov 15 22:38:49 nuc bash[997395]: lite-1               | {"level":30,"time":1731706729010,"service.version":"66708df","path":"imported-user-segment","err":{"type":"Error","message":"Lexical error on line 1. Unrecognized text.\n$.imported-user-segment\n----------^","stack":"Error: Lexical error on line 1. Unrecognized text.\n$.imported-user-segment\n----------^\n    at Parser.parseError (/service/node_modules/jsonpath/generated/parser.js:166:15)\n    at Parser.parser.yy.parseError (/service/node_modules/jsonpath/lib/parser.js:13:17)\n    at Object.parseError (/service/node_modules/jsonpath/generated/parser.js:341:28)\n    at Object.next (/service/node_modules/jsonpath/generated/parser.js:595:25)\n    at Object.lex (/service/node_modules/jsonpath/generated/parser.js:605:22)\n    at lex (/service/node_modules/jsonpath/generated/parser.js:194:28)\n    at Parser.parse (/service/node_modules/jsonpath/generated/parser.js:207:26)\n    at JSONPath.parse (/service/node_modules/jsonpath/lib/index.js:17:22)\n    at toJsonPathParam (/service/packages/isomorphic-lib/dist/src/jsonPath.js:19:28)\n    at toJsonPathParamCh (/service/packages/backend-lib/dist/src/computedProperties/computePropertiesIncremental.js:864:57)"},"msg":"invalid json path in node path"}
Nov 15 22:38:49 nuc bash[997395]: lite-1               | {"level":30,"time":1731706729016,"service.version":"66708df","path":"imported-user-segment","err":{"type":"Error","message":"Lexical error on line 1. Unrecognized text.\n$.imported-user-segment\n----------^","stack":"Error: Lexical error on line 1. Unrecognized text.\n$.imported-user-segment\n----------^\n    at Parser.parseError (/service/node_modules/jsonpath/generated/parser.js:166:15)\n    at Parser.parser.yy.parseError (/service/node_modules/jsonpath/lib/parser.js:13:17)\n    at Object.parseError (/service/node_modules/jsonpath/generated/parser.js:341:28)\n    at Object.next (/service/node_modules/jsonpath/generated/parser.js:595:25)\n    at Object.lex (/service/node_modules/jsonpath/generated/parser.js:605:22)\n    at lex (/service/node_modules/jsonpath/generated/parser.js:194:28)\n    at Parser.parse (/service/node_modules/jsonpath/generated/parser.js:207:26)\n    at JSONPath.parse (/service/node_modules/jsonpath/lib/index.js:17:22)\n    at toJsonPathParam (/service/packages/isomorphic-lib/dist/src/jsonPath.js:19:28)\n    at toJsonPathParamCh (/service/packages/backend-lib/dist/src/computedProperties/computePropertiesIncremental.js:864:57)"},"msg":"invalid json path in node path"}
```
I'm not sure whether it's giving the error when parsing the users or the property itself.

**Comment by walseb** [comment]
One unrelated thing is that Dittofeed recreates a lot of the user properties I delete whenever it restarts. It could be because they are referenced in the initial template that comes with Dittofeed? Or it's related to this bug.

**Comment by maxgurewitz** [comment]
@walseb it's probably because you have not disabled bootstrapping. Try setting `BOOTSTRAP` to be false in your docker compose file. Should already be there, just uncomment it.

**Comment by maxgurewitz** [comment]
> Yes, the issue is with the worker. It's getting a syntax error when parsing:

What's in your `imported-user-segment`?

**Comment by walseb** [comment]
> > Yes, the issue is with the worker. It's getting a syntax error when parsing:
> 
> What's in your `imported-user-segment`?

I'm not sure, it should be just a single digit, but I might have put something strange in there. 

How would I access the data of the property worker?

**Comment by walseb** [comment]
> > One unrelated thing is that Dittofeed recreates a lot of the user properties I delete whenever it restarts. It could be because they are referenced in the initial template that comes with Dittofeed? Or it's related to this bug.
> 
> @walseb it's probably because you have not disabled bootstrapping. Try setting `BOOTSTRAP` to be false in your docker compose file. Should already be there, just uncomment it.

That's great, thank you!

**Comment by maxgurewitz** [comment]
@walseb can you post these questions on our help channel? Going to close this thread for now

https://discord.com/channels/1182801141046726706/1182813628806729748
