### ISSUE TITLE
Git clone url is incorrect in the docs

### ISSUE THREAD

**Issue by shekhar677** [dittofeed/dittofeed#1145]
❌ git clone git@github.com:dittofeed/dittofeed.git
✅ git clone https://github.com/dittofeed/dittofeed.git

**Comment by maxgurewitz** [comment]
Hi @shekhar677 this isn't wrong, it's just that there are two ways to clone a repo, via https or ssh i.e.

- SSH: git@github.com:dittofeed/dittofeed.git
- https: https://github.com/dittofeed/dittofeed.git

both ways work!

**Comment by shekhar677** [comment]
> Hi @shekhar677 this isn't wrong, it's just that there are two ways to clone a repo, via https or ssh i.e.
> 
> * SSH: [git@github.com](mailto:git@github.com):dittofeed/dittofeed.git
> * https: https://github.com/dittofeed/dittofeed.git
> 
> both ways work!

oh, got it. 👍🏻
