### ISSUE TITLE
Deploy Error with Docker Compose

### ISSUE THREAD

**Issue by chandantiwari** [dittofeed/dittofeed#260]
I am using EC2 instance with Amazon Linux and getting the following error. 
<img width="1119" alt="Screenshot 2023-06-29 at 14 43 33" src="https://github.com/dittofeed/dittofeed/assets/4123626/37eeb0f4-6e64-4c9c-8fd3-ced1897675ac">

Am I doing something wrong?

**Comment by maxgurewitz** [comment]
Hi @chandantiwari! What version of the admin-cli are you on? If you're not on [v0.0.18](https://github.com/dittofeed/dittofeed/releases/tag/v0.0.18) can you pull and try again?

**Comment by chandantiwari** [comment]
I will check this and let you know.

**Comment by maxgurewitz** [comment]
Going to close this as I haven't gotten a response @chandantiwari . Feel free to re-open, or ping on slack if you encounter again!
