### ISSUE TITLE
Docker Self-Host: ApiBase value is wrong.

### ISSUE THREAD

**Issue by vikas5914** [dittofeed/dittofeed#486]
Hi, 

We have deployed using `Self-Host with Docker Compose`. However, the value of API base is coming as `"apiBase": "http://localhost:3001"`

Can you please provide how to set this value in docker-compose? 

![image](https://github.com/dittofeed/dittofeed/assets/7912297/c3dbe200-613a-4237-9c63-9e653458e150)

**Comment by maxgurewitz** [comment]
@vikas5914 thanks for the issue! The docker compose setup supports overriding `apiBase` using the `DASHBOARD_API_BASE` env variable. I'll be sure to update our docs with a relevant example.

**Comment by maxgurewitz** [comment]
@vikas5914 this PR should address this issue https://github.com/dittofeed/dittofeed/pull/487! Going to close it. Make sure to git pull on your side. If you have any more questions, or run into more problems feel free to let me know either with another issue or in slack! Thanks!
