### ISSUE TITLE
[Feat] Management API for Templates

### ISSUE THREAD

**Issue by mrvdot** [dittofeed/dittofeed#545]
Apologies if I missed this somewhere, but I searched through all the docs and couldn't find it.

Would be great to have a way to manage templates (really everything) via an API. For example, I've got a platform that already has a way for users to build email templates (in a more WYSIWYG way), but I'd love to use Dittofeed for the eventing and sending of messages. Ideally, I'd just `POST`/`PUT` the template when they edit it, and otherwise let them build their workflows/etc the same way. 

Similarly, I'd love to be able to embed various parts of the dittofeed admin/management area within the app. If it was directly embeddable, that'd be nice, but I could also make do with an API as well.

Thanks!

**Comment by maxgurewitz** [comment]
Welcome @mrvdot !

> Would be great to have a way to manage templates (really everything) via an API. For example, I've got a platform that already has a way for users to build email templates (in a more WYSIWYG way), but I'd love to use Dittofeed for the eventing and sending of messages. Ideally, I'd just POST/PUT the template when they edit it, and otherwise let them build their workflows/etc the same way.

Yes, this is available, but not well documented. I'll be sure to update our documentation!

> Similarly, I'd love to be able to embed various parts of the dittofeed admin/management area within the app. If it was directly embeddable, that'd be nice, but I could also make do with an API as well.

Embeddable components are definitely something we've had a few people request, and we may build them in the future, but they're likely a far ways off.  For a full list of the available API's before full documentation is available, check out this file.

https://github.com/dittofeed/dittofeed/blob/main/packages/api/src/buildApp/router.ts, and in particular this controller, https://github.com/dittofeed/dittofeed/blob/main/packages/api/src/controllers/contentController.ts

**Comment by mrvdot** [comment]
Great, thanks @maxgurewitz , I'll check out the docs on the management API, that's (hopefully) enough for me for now!
