### ISSUE TITLE
[DF-387] Implement Resend support

### ISSUE THREAD

**Issue by maxgurewitz** [dittofeed/dittofeed#576]
Implement support for [https://resend.com/](https://resend.com/) as an email service provider.

Add a new `PersistedEmailProvider` type:

[https://github.com/dittofeed/dittofeed/blob/01a6db73e237897b7e961c07969ea5d60a8bcbd0/packages/isomorphic-lib/src/types.ts#L991-L994](https://github.com/dittofeed/dittofeed/blob/01a6db73e237897b7e961c07969ea5d60a8bcbd0/packages/isomorphic-lib/src/types.ts#L991-L994)

Add new `EmailServiceProviderSuccess` type:

[https://github.com/dittofeed/dittofeed/blob/01a6db73e237897b7e961c07969ea5d60a8bcbd0/packages/isomorphic-lib/src/types.ts#L1946-L1950C4](https://github.com/dittofeed/dittofeed/blob/01a6db73e237897b7e961c07969ea5d60a8bcbd0/packages/isomorphic-lib/src/types.ts#L1946-L1950C4)

Add new `EmailServiceProviderFailure` type:

[https://github.com/dittofeed/dittofeed/blob/01a6db73e237897b7e961c07969ea5d60a8bcbd0/packages/isomorphic-lib/src/types.ts#L2080-L2083](https://github.com/dittofeed/dittofeed/blob/01a6db73e237897b7e961c07969ea5d60a8bcbd0/packages/isomorphic-lib/src/types.ts#L2080-L2083)

Add new `EmailProviderSecret` type:

[https://github.com/dittofeed/dittofeed/blob/01a6db73e237897b7e961c07969ea5d60a8bcbd0/packages/isomorphic-lib/src/types.ts#L2080-L2083](https://github.com/dittofeed/dittofeed/blob/01a6db73e237897b7e961c07969ea5d60a8bcbd0/packages/isomorphic-lib/src/types.ts#L2080-L2083)A webhook for

Error handling for the `/templates/test` api endpoint:

[https://github.com/dittofeed/dittofeed/blob/01a6db73e237897b7e961c07969ea5d60a8bcbd0/packages/api/src/controllers/contentController.ts#L174-L178](https://github.com/dittofeed/dittofeed/blob/01a6db73e237897b7e961c07969ea5d60a8bcbd0/packages/api/src/controllers/contentController.ts#L174-L178)

A webhook for updating the status of sent emails:

[https://github.com/dittofeed/dittofeed/blob/01a6db73e237897b7e961c07969ea5d60a8bcbd0/packages/api/src/controllers/webhooksController.ts#L23-L24](https://github.com/dittofeed/dittofeed/blob/01a6db73e237897b7e961c07969ea5d60a8bcbd0/packages/api/src/controllers/webhooksController.ts#L23-L24)

Handle the email provider type when sending messages:

[https://github.com/dittofeed/dittofeed/blob/01a6db73e237897b7e961c07969ea5d60a8bcbd0/packages/backend-lib/src/messageTemplates.ts#L479-L481](https://github.com/dittofeed/dittofeed/blob/01a6db73e237897b7e961c07969ea5d60a8bcbd0/packages/backend-lib/src/messageTemplates.ts#L479-L481)

Create the Resend email provider:

[https://github.com/dittofeed/dittofeed/blob/01a6db73e237897b7e961c07969ea5d60a8bcbd0/packages/dashboard/src/lib/email.ts#L86-L100](https://github.com/dittofeed/dittofeed/blob/01a6db73e237897b7e961c07969ea5d60a8bcbd0/packages/dashboard/src/lib/email.ts#L86-L100)

Add Place in Settings to configure email provider:

[https://github.com/dittofeed/dittofeed/blob/01a6db73e237897b7e961c07969ea5d60a8bcbd0/packages/dashboard/src/pages/settings.page.tsx#L847-L854](https://github.com/dittofeed/dittofeed/blob/01a6db73e237897b7e961c07969ea5d60a8bcbd0/packages/dashboard/src/pages/settings.page.tsx#L847-L854)

<sub>From [SyncLinear.com](https://synclinear.com) | [DF-387](https://linear.app/dittofeed/issue/DF-387/implement-resend-support)</sub>

**Comment by neo773** [comment]
Could I get assigned?
/attempt #576
