### ISSUE TITLE
[DF-322] event search

### ISSUE THREAD

**Issue by maxgurewitz** [dittofeed/dittofeed#578]
Implement a search bar in the events page. This should allow you to search events by:

* event name (or page/screen)
* event type
* message id

Selecting an individual event should bring up a sidebar showing the event in greater detail.

Should be featured on the `/dashboard/events` page.

<sub>From [SyncLinear.com](https://synclinear.com) | [DF-322](https://linear.app/dittofeed/issue/DF-322/event-search)</sub>

**Comment by chaos-stotch** [comment]
/attempt #578

Can I be assigned to this?

**Comment by maxgurewitz** [comment]
Done! @chaos-stotch hit us up on Discord when / if you need more info.

**Comment by b4s36t4** [comment]
Adding myself to pipeline if in case this becomes open :)

**Comment by chaos-stotch** [comment]
I'm going to unassign myself, sorry for taking so long.

<details>
  <summary> </summary>
  My computer is too weak to run the application locally and develop at the same time.
</details>

**Comment by oliverqx** [comment]
/attempt #578

Can I be assigned to this?

**Comment by maxgurewitz** [comment]
I'm going to let this issue be open. Anyone can work on it, and the first person to produce a good working solution will earn a bounty.

**Comment by joejanho** [comment]
/attempt #578
Can I pick this?

Few questions
1. any specs for the search, to be more specific will it search for the exact match,  and will it be and/or for the different columns? 
2. event in greater detailm what should it include in terms of additional data, everything that the backend is returning from the events query `SELECT
    workspace_id,
    any(event_type) event_type,
    user_id,
    any(anonymous_id) anonymous_id,
    any(user_or_anonymous_id) user_or_anonymous_id,
    message_id,
    event_time,
    any(processing_time) processing_time,
    any(event) event,
    JSONExtractRaw(any(message_raw), 'traits') AS traits,
    JSONExtractRaw(any(message_raw), 'properties') AS properties`

**Comment by Rutik7066** [comment]
Hey @joejanho I you see my PR i am working on it only one issue is left.
