### ISSUE TITLE
[DF-299] filter users by user property or segment value

### ISSUE THREAD

**Issue by maxgurewitz** [dittofeed/dittofeed#579]
Filter users by user property value or segment value e.g.

* user property - email:name
* segment - new users:true

Should be featured on the `/dashboard/users` page. Will likely require searching over the `computed_property_assignments_v2` clickhouse table, which will likely require a new skip index.

The filtering UX should be modeled after Linear's filtering, as shown below.

[https://www.loom.com/share/97674e0a0aea4c459f768fc21ea2199c?sid=da3456c0-e48b-4045-97e8-855b7d937330](https://www.loom.com/share/97674e0a0aea4c459f768fc21ea2199c?sid=da3456c0-e48b-4045-97e8-855b7d937330)

The `computed_property_assignments_v2`table should be queried by providing values for all columns in the sort key,

```
(workspace_id, type, computed_property_id, user_id)
```

<sub>From [SyncLinear.com](https://synclinear.com) | [DF-299](https://linear.app/dittofeed/issue/DF-299/filter-users-by-user-property-or-segment-value)</sub>

**Comment by sy425191** [comment]
Hey @maxgurewitz, can you clarify 1 important query pls. We can only search with either only 1 user property (i.e. name, email) or only 1 segment (i.e: new user:true) at a time, right?

**Comment by tobihans** [comment]
Can I get assigned to this, please, as sy425191 can not continue ?

**Comment by maxgurewitz** [comment]
@sy425191 

> Hey @maxgurewitz, can you clarify 1 important query pls. We can only search with either only 1 user property (i.e. name, email) or only 1 segment (i.e: new user:true) at a time, right?

For this ticket, you should be able to search with multiple values, which should be treated as AND conditionals.

**Comment by oliverqx** [comment]
@Rutik7066 I'm already working on a solution, its nearly done
