### ISSUE TITLE
[DF-362] ensure internal user properties are not rendered on user page

### ISSUE THREAD

**Issue by maxgurewitz** [dittofeed/dittofeed#580]
When on the `/dashboard/users` page or the `/dashboard/users/[id]` page, user properties with the `Internal` `resourceType` should not be rendered.

<sub>From [SyncLinear.com](https://synclinear.com) | [DF-362](https://linear.app/dittofeed/issue/DF-362/ensure-internal-user-properties-are-not-rendered-on-user-page)</sub>

**Comment by rajdip-b** [comment]
/attempt #580 can I be assigned? @chandlercraig

**Comment by rishi-raj-jain** [comment]
/attempt #580

Can I be assigned?
