### ISSUE TITLE
[DF-317] Provide default From address for email templates

### ISSUE THREAD

**Issue by maxgurewitz** [dittofeed/dittofeed#581]
Create a section of `/dashboard/settings` in which users can set a default "From" address for emails. When creating new email templates, the From section should be populated with this value by default.

<sub>From [SyncLinear.com](https://synclinear.com) | [DF-317](https://linear.app/dittofeed/issue/DF-317/provide-default-from-address-for-email-templates)</sub>

**Comment by tobihans** [comment]
@raghavyuva FYI, I'm working on it. Thanks
