### ISSUE TITLE
[DF-316] see journey branch percentages

### ISSUE THREAD

**Issue by maxgurewitz** [dittofeed/dittofeed#582]
Amend the `/journeys/stats` endpoint to include the proportion of users that traverse along a given path within a journey.

Render these proportions as percentages on Journeys.

These percentages can be calculated by querying the `user_events_v2 clickhouse` table for `DFJourneyNodeProcessed` events which are tracked here.

[https://github.com/dittofeed/dittofeed/blob/b621cd2aeb15a86cf08f3cc1b9a285f91c2a0efd/packages/backend-lib/src/journeys/userWorkflow/activities.ts#L885-L896](https://github.com/dittofeed/dittofeed/blob/b621cd2aeb15a86cf08f3cc1b9a285f91c2a0efd/packages/backend-lib/src/journeys/userWorkflow/activities.ts#L885-L896)

![Screen Shot 2024-01-20 at 4.05.37 PM.png](https://uploads.linear.app/a76e221b-dd2e-4f82-9616-842f0e3df86e/dc179e15-0904-435b-bbe7-60cd0f3cffc1/f87eac6c-dcc9-4640-9db8-f42f5a3f2982?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2E3NmUyMjFiLWRkMmUtNGY4Mi05NjE2LTg0MmYwZTNkZjg2ZS9kYzE3OWUxNS0wOTA0LTQzNWItYmJlNy02MGNkMGYzY2ZmYzEvZjg3ZWFjNmMtZGNjOS00NjQwLTlkYjgtZjQyZjVhM2YyOTgyIiwiaWF0IjoxNzA1Nzk1ODUyLCJleHAiOjE3MDU4ODIyNTJ9.cq_h-k9YLV__ujF96akO_w0PlTG\_-3ezSrDy3FPsWsU)

<sub>From [SyncLinear.com](https://synclinear.com) | [DF-316](https://linear.app/dittofeed/issue/DF-316/see-journey-branch-percentages)</sub>

**Comment by mrkirthi-24** [comment]
@maxgurewitz What is the submission deadline?

**Comment by chandlercraig** [comment]
@mrkirthi-24 thanks for giving this a shot! Deadline is 1 week from the start of your attempt.

**Comment by sy425191** [comment]
I would love to /attempt #582 and share updates frequently

**Comment by mrkirthi-24** [comment]
Hi @maxgurewitz I am not clear about the issue. Can you please elaborate it? I would help me understand better.

**Comment by maxgurewitz** [comment]
@mrkirthi-24 yes I'll add greater detail!

**Comment by maxgurewitz** [comment]
@mrkirthi-24 is that enough info?
