### ISSUE TITLE
[DF-415] create paginated table for resource list views

### ISSUE THREAD

**Issue by maxgurewitz** [dittofeed/dittofeed#583]
Create table component for paginated resource list views:

* `/dashboard/templates`
* `/dashboard/segments`
* `/dashboard/journeys`
* `/dashboard/broadcasts`
* `/dashboard/user-properties`

Component should have columns for

* Name
* Updated At

and allow for additional columns e.g.

### Segments

* Journeys Used By
* Last Re-Computed

### Templates

* Journeys Used By

### User Properties

* Last Re-Computed
* Templates Used By

### Broadcasts

* Sent At

<sub>From [SyncLinear.com](https://synclinear.com) | [DF-415](https://linear.app/dittofeed/issue/DF-415/create-paginated-table-for-resource-list-views)</sub>

**Comment by maxgurewitz** [comment]
Hi all, how are these attempts coming along? Anyone need help?

**Comment by mrkirthi-24** [comment]
> Hi all, how are these attempts coming along? Anyone need help?

@maxgurewitz I am waiting for @b4s36t4. I will take the issue, if he is not working on this one.

**Comment by maxgurewitz** [comment]
@mrkirthi-24 feel free to attempt!
