### ISSUE TITLE
[DF-417] allow individual users to be deleted in the ui

### ISSUE THREAD

**Issue by maxgurewitz** [dittofeed/dittofeed#591]
Add a delete button in the `/dashboard/users/[id]` page to hit the `DELETE /api/users` endpoint. Make sure it has a confirmation modal.

<sub>From [SyncLinear.com](https://synclinear.com) | [DF-417](https://linear.app/dittofeed/issue/DF-417/allow-individual-users-to-be-deleted-in-the-ui)</sub>

**Comment by Japosh702** [comment]
What exactly are we meant to do?

**Comment by mrkirthi-24** [comment]
![Screenshot 2024-01-19 at 2 53 50 PM](https://github.com/dittofeed/dittofeed/assets/53830546/8c934ffd-7586-4be5-9061-3ce51cd56acc)

Where should i add the button??

**Comment by maxgurewitz** [comment]
@mrkirthi-24 I'd create a `...` dropdown containing a delete button. Let's put the button in the upper right corner, at the same height as the "Segments" and "Events" headers.

**Comment by mrkirthi-24** [comment]
Got it @maxgurewitz

**Comment by mrkirthi-24** [comment]
Hi @maxgurewitz how do i create a user?

![Screenshot 2024-01-20 at 5 08 28 PM](https://github.com/dittofeed/dittofeed/assets/53830546/7a047a36-3c9c-4d86-badd-ad71ea3c26a4)

**Comment by maxgurewitz** [comment]
@mrkirthi-24 added this to the FAQ section for you!

https://docs.dittofeed.com/contributing/running-locally#why-dont-i-see-any-users-in-the-dashboard
