### ISSUE TITLE
[DF-427] add confirmation feedback to “Publish Changes” button in message template view

### ISSUE THREAD

**Issue by maxgurewitz** [dittofeed/dittofeed#620]
![Screenshot 2024-02-01 at 12.47.29 PM.png](https://uploads.linear.app/a76e221b-dd2e-4f82-9616-842f0e3df86e/015a7ba6-b024-4d9b-987b-1614f7f7f3a6/d2b0529a-a9cf-4c81-b116-6a4d47179144?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2E3NmUyMjFiLWRkMmUtNGY4Mi05NjE2LTg0MmYwZTNkZjg2ZS8wMTVhN2JhNi1iMDI0LTRkOWItOTg3Yi0xNjE0ZjdmN2YzYTYvZDJiMDUyOWEtYTljZi00YzgxLWIxMTYtNmE0ZDQ3MTc5MTQ0IiwiaWF0IjoxNzA2ODIzMTAwLCJleHAiOjE3MDY5MDk1MDB9.16mLZTPEBHO89lTmFk499J8ijDVS_L7qvMDfIsF5rmk)

When changes have been published, this check icon should appear beside the "Publish Changes" text:

[https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Acheck_circle_outline%3A](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Acheck_circle_outline%3A)

When changes haven't been published, the check icon should disappear

<sub>From [SyncLinear.com](https://synclinear.com) | [DF-427](https://linear.app/dittofeed/issue/DF-427/add-confirmation-feedback-to-publish-changes-button-in-message)</sub>

**Comment by Kacppian** [comment]
Can I pick this up?

**Comment by chandlercraig** [comment]
> Can I pick this up?

Yes 👍🏽

**Comment by anoopw3bdev** [comment]
Hi @Kacppian are you working on this issue? if not I would like to work on this
