### ISSUE TITLE
[DF-428] make user properties collapsible in template view

### ISSUE THREAD

**Issue by chandlercraig** [dittofeed/dittofeed#621]
When user properties section is collapsed, text editor should expand left:

![image](https://uploads.linear.app/a76e221b-dd2e-4f82-9616-842f0e3df86e/65bac3d3-60de-4fc2-b18a-0b1d0d6cfc72/447aebf7-eca5-4320-b747-c1ffebaf2f96?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2E3NmUyMjFiLWRkMmUtNGY4Mi05NjE2LTg0MmYwZTNkZjg2ZS82NWJhYzNkMy02MGRlLTRmYzItYjE4YS0wYjFkMGQ2Y2ZjNzIvNDQ3YWViZjctZWNhNS00MzIwLWI3NDctYzFmZmViYWYyZjk2IiwiaWF0IjoxNzEyMzM5NTc4LCJleHAiOjE3MTI0MjU5Nzh9.SlAJylPKh3O9IBLJycfnsKqTO4FE3_hakfhzebzP5MA)

Collapse icon should be double left arrows inside of a circle, overlayed on the user properties section's right border (near the top), with a short, informative tooltip:

[https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Akeyboard_double_arrow_left%3A](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Akeyboard_double_arrow_left%3A)

![image](https://uploads.linear.app/a76e221b-dd2e-4f82-9616-842f0e3df86e/14c53d48-3dca-42b9-b05a-75205d209b85/12f336ea-e861-4add-8e95-0190ea60c231?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2E3NmUyMjFiLWRkMmUtNGY4Mi05NjE2LTg0MmYwZTNkZjg2ZS8xNGM1M2Q0OC0zZGNhLTQyYjktYjA1YS03NTIwNWQyMDliODUvMTJmMzM2ZWEtZTg2MS00YWRkLThlOTUtMDE5MGVhNjBjMjMxIiwiaWF0IjoxNzEyMzM5NTc4LCJleHAiOjE3MTI0MjU5Nzh9.UG1owsjYGKavWAZtOOh68F-YKUB4ec7y_evZNLLayK8)

Expand icon should be double right arrows inside of a circle, overlayed on the border between the message editor and the Dittofeed menu bar, with a short, informative tooltip:

[https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Akeyboard_double_arrow_right%3A](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Akeyboard_double_arrow_right%3A)

![image](https://uploads.linear.app/a76e221b-dd2e-4f82-9616-842f0e3df86e/96fcbbf4-7625-43ac-a5be-65e48933f80c/51d59327-0c7e-4f0e-ae8a-da7032e203ac?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiL2E3NmUyMjFiLWRkMmUtNGY4Mi05NjE2LTg0MmYwZTNkZjg2ZS85NmZjYmJmNC03NjI1LTQzYWMtYTViZS02NWU0ODkzM2Y4MGMvNTFkNTkzMjctMGM3ZS00ZjBlLWFlOGEtZGE3MDMyZTIwM2FjIiwiaWF0IjoxNzEyMzM5NTc4LCJleHAiOjE3MTI0MjU5Nzh9.VMCB1_0lp0v9BmdssAxC0Ms_SuQRfkRQfBD4iRI24rw)

"Publish Changes" and "Send Test Message" buttons should appear as the following icons respectively, also inside of circles, overlayed on the same border as the expand icon (vertically, below expand button), with short, informative tooltips:

1. Publish Changes [https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Apublish%3A](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Apublish%3A)
2. Send Test Message [https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Aforward_to_inbox%3A](https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Aforward_to_inbox%3A)

<sub>From [SyncLinear.com](https://synclinear.com) | [DF-428](https://linear.app/dittofeed/issue/DF-428/make-user-properties-collapsible-in-template-view)</sub>

**Comment by Kacppian** [comment]
I can take up this and #620 since they're both similar areas of work? I'll obviously submit 2 different prs though

**Comment by chandlercraig** [comment]
Sounds good, thanks Kaushik! Let me know if you have any questions.

**Comment by melsonic** [comment]
sorry I didn't see @Kacppian is already working on this

**Comment by KrishavRajSingh** [comment]
I would like to work on this

**Comment by Pradumn27** [comment]
Hey @Kacppian can I get this assigned?

**Comment by Kacppian** [comment]
I will be submitting the PR today. Sorry for the delay, had a pretty rough week

**Comment by vinfinity7** [comment]
@chandlercraig whats up with this ?

**Comment by maxgurewitz** [comment]
@vinfinity7, @Kacppian is busy so if you want to pick up from where he left off 
https://github.com/dittofeed/dittofeed/pull/648
that'd be amazing 🙏

**Comment by vinfinity7** [comment]
ohk @maxgurewitz , ill get into this rightaway

**Comment by maxgurewitz** [comment]
closed here https://github.com/dittofeed/dittofeed/issues/621
