### ISSUE TITLE
[DF-435] create a "preview" column in the deliveries table

### ISSUE THREAD

**Issue by maxgurewitz** [dittofeed/dittofeed#634]
Modify the `packages/dashboard/src/components/deliveriesTable.tsx` component by adding a preview column. This column should use an "eye" icon.

Clicking on this column should bring up a full screen preview of what the delivery looked like for users. This should reuse the preview portion of the `packages/dashboard/src/components/templateEditor.tsx` component, including the rising animation.

<sub>From [SyncLinear.com](https://synclinear.com) | [DF-435](https://linear.app/dittofeed/issue/DF-435/create-a-preview-column-in-the-deliveries-table)</sub>

**Comment by jemiluv8** [comment]
/attempt #634

I've started work on this. can I be assigned?

**Comment by jemiluv8** [comment]
@mehulmathur16, I'm still working on this.

**Comment by mehulmathur16** [comment]
@jemiluv8 I think multiple people can work on the issue, since this issue isn't assigned to someone.

**Comment by jemiluv8** [comment]
@mehulmathur16, kudos. That was quick.

**Comment by mehulmathur16** [comment]
Thanks @jemiluv8👍
