### ISSUE TITLE
[DF-436] persist event page search in url state

### ISSUE THREAD

**Issue by maxgurewitz** [dittofeed/dittofeed#637]
The url state state should include the page number, the page size, the searchTerm, and the currently selected event if there is one for the events table: `packages/dashboard/src/components/eventsTable.tsx`

<sub>From [SyncLinear.com](https://synclinear.com) | [DF-436](https://linear.app/dittofeed/issue/DF-436/persist-event-page-search-in-url-state)</sub>

**Comment by rishi-raj-jain** [comment]
/attempt #637

can i be assigned this?

**Comment by hunxjunedo** [comment]
@maxgurewitz has the issue been resolved ? can I get assigned ?

**Comment by maxgurewitz** [comment]
@hunxjunedo it hasn't been resolved! happy to assign it to you!
