### ISSUE TITLE
[DF-452] don't show 404 for /dashboard/users/[id] if user properties missing

### ISSUE THREAD

**Issue by maxgurewitz** [dittofeed/dittofeed#673]
<sub>From [SyncLinear.com](https://synclinear.com) | [DF-452](https://linear.app/dittofeed/issue/DF-452/dont-show-404-for-dashboardusers[id]-if-user-properties-missing)</sub>

**Comment by Emmanuel0705** [comment]
can i work on this ?

**Comment by maxgurewitz** [comment]
@Emmanuel0705 and @Bhavyajain21 yes feel free to work on it though know it doesn't have a bounty currently!

**Comment by hunxjunedo** [comment]
Hey @maxgurewitz, can I get assigned?

**Comment by maxgurewitz** [comment]
sure @hunxjunedo !

**Comment by hunxjunedo** [comment]
@maxgurewitz I can't open the Linear link, it says I don't have the access to workspace.

**Comment by maxgurewitz** [comment]
Hi @hunxjunedo we're using using a tool called https://synclinear.com/ to sync our teams internal linear tickets to gihub issues. I'll add more details to the ticket / issue! (You shouldn't have / need access to the linear workspace)

**Comment by hunxjunedo** [comment]
Still waiting for you to add details so I can proceed to revolving the issue.
