### ISSUE TITLE
Enhance Default From Address Handling in Message Templates

### ISSUE THREAD

**Issue by danish1112** [dittofeed/dittofeed#816]
**Issue:**
The current default from address behaviour in message templates can lead to conflicts when switching email providers while using the same template.

**Use Case:**
For example, if a user creates a message template with a specific default from address and later switches from SendGrid to SMTP as the email provider, the default from address specified in the template may no longer be valid or appropriate for the new provider, leading to potential delivery issues.

**Proposal:**
To address this issue, we propose implementing dynamic default from address fetching based on the selected email provider. This would ensure consistency and accuracy in default from address usage across different providers. Additionally, providing user guidance and fallback mechanisms will help handle cases where the default address is not specified or cannot be fetched.

**Comment by maxgurewitz** [comment]
I think implementing a dynamic from address may be a fairly large change to the application. How about when you change the default, it alerts you if there are any existing email templates with different from addresses, and gives you the option of updating them?

**Comment by danish1112** [comment]
Absolutely, looks like a reasonable approach. Whenever the default from address is changed in the settings, we will check all existing message templates and update the from address accordingly. Additionally, we will display a success message to inform users that their message templates have been updated. 

Before moving forward with implementation, I'd like to confirm if you agree with the proposed approach. Once confirmed, I will proceed with implementing the changes as outlined.

**Comment by maxgurewitz** [comment]
@danish1112 apologies for the delayed response!

> Whenever the default from address is changed in the settings, we will check all existing message templates and update the from address accordingly

Before performing the update, we should check if there are any templates with a different email and we should open up a modal giving the user the option to override existing templates (but not perform the override behavior by default).

**Comment by danish1112** [comment]
Got it, I'll work on implementing this feature.

**Comment by danish1112** [comment]
Kindly check this PR @maxgurewitz 

https://github.com/dittofeed/dittofeed/pull/825
