### ISSUE TITLE
/dashboad/events errors out with a client exception

### ISSUE THREAD

**Issue by Heedster** [dittofeed/dittofeed#818]
I deployed dittofeed with render and connected it to send track events from our segment account. As events started to arrive, loading events page always results in a frontend crash. 

Browser console reports this:
```
TypeError: Cannot read properties of null (reading 'journeyId')
    at G (events-eadfafb0b5ef748e.js:1:3782)
    at Object.renderCell (events-eadfafb0b5ef748e.js:1:4648)
    at 7271-611cc4c3d29c6cc6.js:63:24093
    at 7271-611cc4c3d29c6cc6.js:63:26369
    at ab (framework-f29e48ae95cae5a3.js:9:60916)
    at uo (framework-f29e48ae95cae5a3.js:9:71227)
    at i (framework-f29e48ae95cae5a3.js:9:121559)
    at oO (framework-f29e48ae95cae5a3.js:9:99113)
    at framework-f29e48ae95cae5a3.js:9:98980
    at oF (framework-f29e48ae95cae5a3.js:9:98987)
```
Looking at some relevant sections of the stacktrace tells me the original is the 3rd line here
```
G = e=>{
                var t, n;
                let r = e.journeyId || ""
                  , i = e.nodeId || "";
                if ("broadcast-message" === i) {
                    let e = z(r);
                    return e
                }
                let s = e.templateId || ""
                  , a = A.find(e=>e.id === s)
                  , o = null !== (t = null == a ? void 0 : a.type) && void 0 !== t ? t : null
                  , u = null !== (n = null == a ? void 0 : a.name) && void 0 !== n ? n : null
                  , c = W(r, s, u, o);
                return c
```

After a few thousand events, the events page started to load fine, but when i search for something it crashes.

**Comment by maxgurewitz** [comment]
Hi @Heedster I'll take a look!

**Comment by maxgurewitz** [comment]
@Heedster can you try updating to https://github.com/dittofeed/dittofeed/releases/tag/v0.13.2 and seeing if the issue is fixed for you!

**Comment by Heedster** [comment]
Yep. Seems to work fine with 0.13.2

**Comment by maxgurewitz** [comment]
Woo!

**Comment by Heedster** [comment]
Sorry, I spoke too soon, it does not happen anymore when the events page load or when i searched the same thing i searched before, but the same errors happen when i search some other things in the events page.

**Comment by maxgurewitz** [comment]
Are you sure it's the same error?

**Comment by Heedster** [comment]
No, it seems fine now, i think some browser cache messed up in one of my open tabs, hence i felt it resurfaced.

**Comment by maxgurewitz** [comment]
@Heedster sounds good!
