### ISSUE TITLE
Implement GTE and LTE operators for numeric user traits and event properties

### ISSUE THREAD

**Issue by sintezcs** [dittofeed/dittofeed#990]
It will be really useful to have `>=` and `<=` operators for building segments. There are a lot of scenarios for them, e.g.:

`User Trait age >= 30`
or
`User Performed purchase_event at least 1 time
  where made_purchase.price <= 100`

**Comment by maxgurewitz** [comment]
Hey Alex, thanks for this! We'll try to implement them soon :)

**Comment by sintezcs** [comment]
That would be great!

**Comment by maxgurewitz** [comment]
@sintezcs just implemented these features for your team, will go out in the next release!

https://github.com/dittofeed/dittofeed/commit/af4aaf087cf77717c0e54eb9665c2c2ec82db36f
https://github.com/dittofeed/dittofeed/commit/c11c6e4ca11fe945f9d7d1b0ab8ead251c5a3af9
