### ISSUE TITLE
Support for customizing email headers

### ISSUE THREAD

**Issue by walseb** [dittofeed/dittofeed#994]
Is there any way to add headers to the email, like `X-PM-Message-Stream: broadcast`? 

That's necessary to select which channel to send the email from when using Postmark.

I didn't see any option for this in the broadcast email editor. 

Thanks!

**Comment by maxgurewitz** [comment]
HI @walseb no support yet, but we can definitely add support for arbitrary email headers!

**Comment by walseb** [comment]
Thank you for the answer! 

In the meanwhile I think having only one message stream per channel in Postmark solves the issue, but then you would have to switch account to select a different message stream.

**Comment by walseb** [comment]
Actually, you can't delete the default transactional message stream in Postmark, which means you aren't able to send messages through the broadcast stream in Postmark with this service. 

The only solution before the custom header feature is implemented is to send messages via SMTP and generate an SMTP token to the message stream you want to use in Postmark.

![2024-08-22 Thu 22:23 p6HxlM](https://github.com/user-attachments/assets/130630cb-10da-4a28-909f-7bbc0bf2ca2f)

**Comment by walseb** [comment]
To clarify, the email editor needs to support adding custom email headers. It can't be in the settings because it needs to be able to be different for each campaign, so you can assign tags, send to different Postmark streams, etc.

**Comment by maxgurewitz** [comment]
Yes, of course!

**Comment by vikashsprem** [comment]
Hey @walseb, could you please assign me? So that I will start working on it.

**Comment by walseb** [comment]
> Hey @walseb, could you please assign me? So that I will start working on it.

Sure, do I have access to do this @maxgurewitz? If so, how do I do this?

**Comment by walseb** [comment]
> ## 💎 $30 bounty [• walseb](https://console.algora.io/org/walseb0)
> ### Steps to solve:
> 
>     1. **Start working**: Comment `/attempt #994` with your implementation plan
> 
>     2. **Submit work**: Create a pull request including `/claim #994` in the PR body to claim the bounty
> 
>     3. **Receive payment**: 100% of the bounty is received 2-5 days post-reward. [Make sure you are eligible for payouts](https://docs.algora.io/bounties/payments#supported-countries-regions)
> 
> 
> Thank you for contributing to dittofeed/dittofeed!
> 
> **[Add a bounty](https://console.algora.io/org/walseb0/bounties/community?fund=dittofeed%2Fdittofeed%23994)** • **[Share on socials](https://twitter.com/intent/tweet?text=%2430+bounty%21+%F0%9F%92%8E+https%3A%2F%2Fgithub.com%2Fdittofeed%2Fdittofeed%2Fissues%2F994&related=algoraio)**

Perhaps simply typing the /attempt command is enough to reserve it.

**Comment by walseb** [comment]
@vikashsprem Did it work? Did you need to be assigned to this issue via GitHub assignments?

**Comment by vikashsprem** [comment]
No, that's fine, I am working on it and I will submit a PR very soon.

**Comment by maxgurewitz** [comment]
Hi @walseb https://github.com/dittofeed/dittofeed/pull/1022/files will go out in the next release!

**Comment by walseb** [comment]
That's great news, thank you so much!

How do I proceed with the bounty? I think it's supposed to activate when a pull request with a claim gets merged?

Thoughts?

**Comment by maxgurewitz** [comment]
@walseb in this case, let's just close it! No need to reward it.

**Comment by weirdo-github** [comment]
I'd like to work on this. I've submitted a PR here: https://github.com/dittofeed/dittofeed/pull/1841

Let me know if there's anything you'd like me to adjust.
